version: '3'
services:
  nginx:
    container_name: web
    image: nginx:latest
    ports:
      - 9999:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
    environment:
      DOCKER_ENV: true

  php:
    container_name: php
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db
    environment:
      DOCKER_ENV: true
      MYSQL_DATABASE: 'my_db'  # 作成するデータベース名
      MYSQL_USER: 'admin'         # 作業ユーザー名→上記データベースの捜査権限をもつ
      MYSQL_PASSWORD: 'admin_pass'          # 作業ユーザーのパスワード
      MYSQL_ROOT_PASSWORD: 'password'   # rootユーザーのパスワード

  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:latest
    ports:
      - 13306:3306
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d # DBの初期データ
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf # bashで日本語文字化けする問題の解決
    environment:
      MYSQL_DATABASE: 'my_db'  # 作成するデータベース名
      MYSQL_USER: 'admin'         # 作業ユーザー名→上記データベースの捜査権限をもつ
      MYSQL_PASSWORD: 'admin_pass'          # 作業ユーザーのパスワード
      MYSQL_ROOT_PASSWORD: 'password'   # rootユーザーのパスワード
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  phpmyadmin:
    container_name: admin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db #mysqlサービス名を指定
    ports:
      - 8888:80
    depends_on:
      - db